name: tb_pipeline
channels:
  - default
  - conda-forge
  - bioconda
dependencies:
  - python
  - snakemake-minimal >=7.3
  - bcftools =1.17
  - samtools =1.15
  - bwa =0.7.17
  - pysam =0.19
  - pygments
  - pandas
  - ivar
  - snippy
  - tabixpp==1.1.0
