name: root
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - numpy
  - biopython
  - matplotlib
  - bwa
  - samtools
  - bedtools
  - ivar>=1.3.1
  - nextalign
  - mafft
  - snakemake-minimal
  