samples:
  H.influenzae: seqs/H.influenzae.fa
  H37Rv: seqs/H37Rv.fa
  K.pneumoniae: seqs/K.pneumoniae.fa
  M.abscessus: seqs/M.abscessus.fa
  M.canetti: seqs/M.canetti.fa
  M.fortuitum: seqs/M.fortuitum.fa
  M.intracellulare: seqs/M.intracellulare.fa
  OXC141: seqs/OXC141.fa
  PA01: seqs/PA01.fa
  S.aureus: seqs/S.aureus.fa
  S.odontolytica: seqs/S.odontolytica.fa